Config = {}

Config.Locale = 'en'
Config.EnableESXIdentity = true
Config.ESXtrigger = 'esx:getSharedObject'
Config.MenuSkintrigger = 'esx_skin:openSaveableMenu'
Config.MaxSalary = 15000
Config.Withdraw = true ---can Withdraw money?if you want ,you can disable it to stop abuse
Config.WithdrawMsg = ' Be dalil bi janbe bazi khodetoon felan offe' -- if Config.Withdraw is false
Config.TpCoords = vector3(-811.84393310547, 175.19441223145, 76.745376586914) -- coords for set clothes
Config.heading = 111.54900360107 -- heading for tp
Config.OpenBossMenu = 'esx_society:openBossMenu' -- you can change it,dont forget to change this in your jobs to.
Config.Inventory = {
    'police',
    'sheriff',
    'fbi',
    'government',
    'army',
    'artesh',
    'mechanic',
    'cia',
    'dadgostari',
}
Config.Offjobs = {
    'police',
    'sheriff',
    'fbi',
    'government',
    'army',
    'artesh',
    'mechanic',
    'cia',
    'dadgostari',
    'ambulance',
    'offpolice',
    'offsheriff',
    'offfbi',
    'offgovernment',
    'offarmy',
    'offartesh',
    'offmechanic',
    'offcia',
    'offdadgostari',
    'offambulance'
}
Config.Armory = {
    ['police'] = {
        'WEAPON_PISTOL',
        'WEAPON_HEAVYPISTOL',
        'WEAPON_COMBATPISTOL',
        'WEAPON_PISTOL50',
        'WEAPON_SNSPISTOL',
        'WEAPON_NIGHTSTICK',
        'WEAPON_STUNGUN',
        'WEAPON_SMG',
        'WEAPON_CARBINERIFLE',
    },
    ['fbi'] = {
        'WEAPON_PISTOL',
        'WEAPON_HEAVYPISTOL',
        'WEAPON_COMBATPISTOL',
        'WEAPON_PISTOL50',
        'WEAPON_SNSPISTOL',
        'WEAPON_NIGHTSTICK',
        'WEAPON_STUNGUN',
        'WEAPON_CARBINERIFLE',
        'WEAPON_ADVANCEDRIFLE',
        'WEAPON_SPECIALCARBINE',
        'WEAPON_SMG',
    },
    ['government'] = {
        'WEAPON_PISTOL',
        'WEAPON_HEAVYPISTOL',
        'WEAPON_COMBATPISTOL',
        'WEAPON_PISTOL50',
        'WEAPON_SNSPISTOL',
        'WEAPON_NIGHTSTICK',
        'WEAPON_STUNGUN',
        'WEAPON_SPECIALCARBINE',
        'WEAPON_ADVANCEDRIFLE',
        'WEAPON_SMG',
        'WEAPON_COMPACTRIFLE',
        'WEAPON_COMBATMG',
        'WEAPON_HEAVYSNIPER',
    },
    ['sheriff'] = {
        'WEAPON_PISTOL',
        'WEAPON_HEAVYPISTOL',
        'WEAPON_COMBATPISTOL',
        'WEAPON_PISTOL50',
        'WEAPON_SNSPISTOL',
        'WEAPON_NIGHTSTICK',
        'WEAPON_STUNGUN',
        'WEAPON_SPECIALCARBINE',
        'WEAPON_PUMPSHOTGUN',
        'WEAPON_SMG',
        'WEAPON_CARBINERIFLE'
    },
    ['dadgostari'] = {
        'WEAPON_PISTOL',
        'WEAPON_HEAVYPISTOL',
        'WEAPON_COMBATPISTOL',
        'WEAPON_PISTOL50',
        'WEAPON_SNSPISTOL',
        'WEAPON_NIGHTSTICK',
        'WEAPON_STUNGUN',
        'WEAPON_SMG',
        'WEAPON_CARBINERIFLE',
        'WEAPON_APPISTOL',
        'WEAPON_MICROSMG',
        'WEAPON_SPECIALCARBINE',
    },
    ['artesh'] = {
        'WEAPON_PISTOL',
        'WEAPON_HEAVYPISTOL',
        'WEAPON_COMBATPISTOL',
        'WEAPON_PISTOL50',
        'WEAPON_SNSPISTOL',
        'WEAPON_NIGHTSTICK',
        'WEAPON_STUNGUN',
        'WEAPON_HEAVYSNIPER',
        'WEAPON_CARBINERIFLE',
        'WEAPON_ADVANCEDRIFLE',
        'WEAPON_SPECIALCARBINE',
        'WEAPON_SMG',
    },
    ['army'] = {
        'WEAPON_PISTOL',
        'WEAPON_HEAVYPISTOL',
        'WEAPON_COMBATPISTOL',
        'WEAPON_PISTOL50',
        'WEAPON_SNSPISTOL',
        'WEAPON_NIGHTSTICK',
        'WEAPON_STUNGUN',
        'WEAPON_HEAVYSNIPER',
        'WEAPON_CARBINERIFLE',
        'WEAPON_ADVANCEDRIFLE',
        'WEAPON_SPECIALCARBINE',
        'WEAPON_SMG',
    },
    ['cia'] = {
        'WEAPON_PISTOL',
        'WEAPON_HEAVYPISTOL',
        'WEAPON_COMBATPISTOL',
        'WEAPON_PISTOL50',
        'WEAPON_SNSPISTOL',
        'WEAPON_NIGHTSTICK',
        'WEAPON_STUNGUN',
        'WEAPON_CARBINERIFLE',
        'WEAPON_ADVANCEDRIFLE',
        'WEAPON_SPECIALCARBINE',
        'WEAPON_SMG',
    },
}
Config.Garage = {
    ['police'] = {
        'police',
        'police2',
        'police3',
        'police4',
        'policeb',
        
    },
    ['fbi'] = {
        'fbi',
        'fbi2',
        'carbonrs',
        'insurgent2',
        'laferrari17',
        'polschafter3',

    },
    ['government'] = {
        'um13tahoe',
        'um14charger',
        'um14ss',
        'um16tahoe',
        'um17f150',
        'um18mustang',
        'umc8',
        'fbi',
        'um20stinger',
        'insurgent2',
        'umbmw',
        'xls2',
        'cognoscenti2',
        'kuruma2',
        'schafter5',
    },
    ['sheriff'] = {
       'sheriff2',
       'sheriff',
       'crusader',
       'barracks3',

    },
    ['artesh'] = {
        'armye63',
        'manchez2',
        'squaddie',
        'riot2',
        'winky',
        'swift',
        'annihilator2',
        'Cargobob',
        'barrage',
        'bf400',
        'policeind',
        'barracks',
        'crusader',


    },
    ['army'] = {
        'crusader',
        'mesa3',
        'barracks',
        'sanchez',
        'gargoyle',
        'bf400',
        'insurgent2',
        'scarab',
        'riot2',
        'cargobob4',
        'buzzard2',
        'insurgent3',
        'nightshark',
        'freecrawler',
        'lazer',
        'savage',
    },
    ['ambulance'] = {
        'ambulance',

    },
    ['weazel'] = {
        'van',
        'rumpo',
    },
    ['mechanic'] = {
        'RAPTOR150',
        'rx7cwest',

    },
    ['dadgostari'] = {
        'xls2',
        'baller6',
        'cog552',
        'schafter5',
        'schafter6',
        'stretch',
    },
    ['cia'] = {
        'fbi',
        'fbi2',
        'neon',
        'baller6',
        -- 'polschafter3',
        'insurgent2',
        'buzzard2',
    },
    ['taxi'] = {
        'superd',
        'taxi',
        'cognoscenti',
        'tailgater',
        'oracle2',
        'superd',
        'buffalo2'
    }
}

Config.MaleDefault = {
    ['bproof_2'] = 0,
    ['helmet_2'] = -1,
    ['chain_2'] = 0,
    ['shoes_1'] = 34,
    ['face_1'] = 0,
    ['age_1'] = 0,
    ['complexion_1'] = 0,
    ['lipstick_4'] = 0,
    ['eyebrows_2'] = 10,
    ['decals_1'] = 0,
    ['glasses_1'] = -1,
    ['arms'] = 15,
    ['bproof_1'] = 0,
    ['makeup_4'] = 0,
    ['hair_color_2'] = 0,
    ['bags_2'] = 0,
    ['watches_1'] = -1,
    ['moles_2'] = 1,
    ['lipstick_3'] = 0,
    ['moles_1'] = 0,
    ['eyebrows_4'] = 12,
    ['arms_2'] = 0,
    ['pants_1'] = 61,
    ['torso_1'] = 15,
    ['torso_2'] = 0,
    ['hair_1'] = 10,
    ['hair_2'] = 0,
    ['hair_color_1'] = 0,
    ['lipstick_1'] = 0,
    ['face_2'] = 21,
    ['beard_3'] = 0,
    ['helmet_1'] = -1,
    ['pants_2'] = 1,
    ['makeup_2'] = 0,
    ['eye_color'] = 0,
    ['mask_1'] = 0,
    ['ears_1'] = -1,
    ['eyebrows_1'] = 0,
    ['glasses_2'] = -1,
    ['bags_1'] = 0,
    ['chain_1'] = 0,
    ['makeup_1'] = 0,
    ['makeup_3'] = 0,
    ['age_2'] = 0,
    ['beard_4'] = 0,
    ['watches_2'] = -1,
    ['complexion_2'] = 1,
    ['decals_2'] = 0,
    ['eyebrows_3'] = 12,
    ['ears_2'] = -1,
    ['face_3'] = 5,
    ['beard_2'] = 10,
    ['tshirt_2'] = 0,
    ['mask_2'] = 2,
    ['beard_1'] = 0,
    ['sex'] = 0,
    ['lipstick_2'] = 0,
    ['tshirt_1'] = 15,
    ['skin'] = 12,
    ['shoes_2'] = 0
}
Config.FemaleDefault = {
    ['bproof_2'] = 0,
    ['helmet_2'] = -1,
    ['chain_2'] = 0,
    ['shoes_1'] = 35,
    ['face_1'] = 0,
    ['arms'] = 15,
    ['complexion_1'] = 0,
    ['lipstick_4'] = 0,
    ['age_1'] = 0,
    ['eyebrows_2'] = 10,
    ['glasses_1'] = -1,
    ['decals_1'] = 0,
    ['bproof_1'] = 0,
    ['torso_2'] = 0,
    ['makeup_4'] = 0,
    ['bags_2'] = 0,
    ['hair_color_2'] = 0,
    ['moles_2'] = 1,
    ['lipstick_3'] = 20,
    ['moles_1'] = 0,
    ['eyebrows_4'] = 12,
    ['arms_2'] = 0,
    ['pants_1'] = 9,
    ['torso_1'] = 16,
    ['watches_1'] = -1,
    ['hair_1'] = 30,
    ['hair_2'] = 0,
    ['hair_color_1'] = 0,
    ['eyebrows_1'] = 1,
    ['face_2'] = 21,
    ['beard_3'] = 0,
    ['helmet_1'] = -1,
    ['pants_2'] = 12,
    ['makeup_2'] = 10,
    ['glasses_2'] = -1,
    ['lipstick_1'] = 3,
    ['ears_1'] = -1,
    ['mask_1'] = 0,
    ['eye_color'] = 0,
    ['bags_1'] = 0,
    ['chain_1'] = 0,
    ['makeup_1'] = 5,
    ['makeup_3'] = 0,
    ['age_2'] = 0,
    ['beard_4'] = 0,
    ['skin'] = 12,
    ['watches_2'] = -1,
    ['decals_2'] = 0,
    ['complexion_2'] = 1,
    ['ears_2'] = -1,
    ['eyebrows_3'] = 26,
    ['beard_2'] = 0,
    ['face_3'] = 6,
    ['mask_2'] = 2,
    ['beard_1'] = 0,
    ['sex'] = 1,
    ['lipstick_2'] = 10,
    ['tshirt_2'] = 0,
    ['tshirt_1'] = 15,
    ['shoes_2'] = 0
}
